.TH ceilometer-agent-central 8
.SH NAME
ceilometer-agent-central \- Please fill

.SH SYNOPSIS
.B ceilometer-agent-central
.B ...params...

.SH DESCRIPTION
.B ceilometer-agent-central

Please fill in a long desc.

.SH PARAMETERS

.LP
.B param1
.IP
Describe here param1

.SH EXAMPLE

.LP
.B Example 1
.IP
Example explanation

.SH AUTHORS

John Doe <john@example.com>
