.TH ceilometer-api 8
.SH NAME
ceilometer-api \- Please fill

.SH SYNOPSIS
.B ceilometer-api
.B ...params...

.SH DESCRIPTION
.B ceilometer-api

Please fill in a long desc.

.SH PARAMETERS

.LP
.B param1
.IP
Describe here param1

.SH EXAMPLE

.LP
.B Example 1
.IP
Example explanation

.SH AUTHORS

John Doe <john@example.com>
