---
sources:
    - name: meter_source
      interval: 600
      meters:
          - "*"
      sinks:
          - meter_sink
    - name: cpu_source
      interval: 600
      meters:
          - "cpu"
      sinks:
          - cpu_sink
    - name: disk_source
      interval: 600
      meters:
          - "disk.read.bytes"
          - "disk.read.requests"
          - "disk.write.bytes"
          - "disk.write.requests"
      sinks:
          - disk_sink
    - name: network_source
      interval: 600
      meters:
          - "network.incoming.bytes"
          - "network.incoming.packets"
          - "network.outgoing.bytes"
          - "network.outgoing.packets"
      sinks:
          - network_sink
    - name: lb_pool_source
      interval: 600
      meters:
          - "network.services.lb.pool"
      discovery:
          - "lb_pools"
      sinks:
          - meter_sink
    - name: lb_health_monitor_source
      interval: 600
      meters:
         - "network.services.lb.health_monitor"
      discovery:
         - "lb_health_probes"
      sinks:
          - meter_sink
    - name: lb_vip_source
      interval: 600
      meters:
          - "network.services.lb.vip"
      discovery:
          - "lb_vips"
      sinks:
          - meter_sink
    - name: lb_member_source
      interval: 600
      meters:
          - "network.services.lb.member"
      discovery:
          - "lb_members"
      sinks:
          - meter_sink
    - name: vpn_services_source
      interval: 600
      meters:
          - "network.services.vpn"
      discovery:
          - "vpn_services"
      sinks:
          - "meter_sink"
    - name: vpn_conns_source
      interval: 600
      meters:
          - "network.services.vpn.connections"
      discovery:
          - "ipsec_connections"
      sinks:
          - "meter_sink"
    - name: firewall_source
      interval: 600
      meters:
          - "network.services.firewall"
      discovery:
          - "fw_services"
      sinks:
          - "meter_sink"
    - name: fw_policy_source
      interval: 600
      meters:
          - "network.services.firewall.policy"
      discovery:
          - "fw_policy"
      sinks:
          - "meter_sink"
sinks:
    - name: meter_sink
      transformers:
      publishers:
          - notifier://
    - name: cpu_sink
      transformers:
          - name: "rate_of_change"
            parameters:
                target:
                    name: "cpu_util"
                    unit: "%"
                    type: "gauge"
                    scale: "100.0 / (10**9 * (resource_metadata.cpu_number or 1))"
      publishers:
          - notifier://
    - name: disk_sink
      transformers:
          - name: "rate_of_change"
            parameters:
                source:
                    map_from:
                        name: "disk\\.(read|write)\\.(bytes|requests)"
                        unit: "(B|request)"
                target:
                    map_to:
                        name: "disk.\\1.\\2.rate"
                        unit: "\\1/s"
                    type: "gauge"
      publishers:
          - notifier://
    - name: network_sink
      transformers:
          - name: "rate_of_change"
            parameters:
                source:
                   map_from:
                       name: "network\\.(incoming|outgoing)\\.(bytes|packets)"
                       unit: "(B|packet)"
                target:
                    map_to:
                        name: "network.\\1.\\2.rate"
                        unit: "\\1/s"
                    type: "gauge"
      publishers:
          - notifier://
