/usr/bin/ceilometer-dbsync
/usr/bin/ceilometer-expirer
/usr/bin/ceilometer-rootwrap
/usr/bin/ceilometer-send-sample
etc/ceilometer/api_paste.ini		/etc/ceilometer
etc/ceilometer/event_definitions.yaml	/etc/ceilometer
etc/ceilometer/pipeline.yaml		/etc/ceilometer
etc/ceilometer/policy.json		/etc/ceilometer
etc/ceilometer/rootwrap.conf		/etc/ceilometer
etc/ceilometer/rootwrap.d/ipmi.filters	/etc/ceilometer/rootwrap.d
tools/show_data.py usr/share/doc/ceilometer
